export const LOAD_FORECAST_SUCCESS = 'LOAD_FORECAST_SUCCESS';
export const LOAD_FORECAST_REQUEST = 'LOAD_FORECAST_REQUEST';
export const LOAD_CITIES_REQUEST = 'LOAD_CITIES_REQUEST';
export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';